### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [mohilles/f1-3-c2p1-colmar-academy#1]
https://github.com/mohilles/f1-3-c2p1-colmar-academy/blob/master/Colmar/index.html#L68

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found here - https://www.w3schools.com/html/html_entities.asp

**Comment by mohilles** [comment]
ok) Thanks
Done!
