### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [mohilles/f1-3-c2p1-colmar-academy#5]
**GRADE**: Exceeds Expectations

**SUMMARY**: Excellent work on this project! The site itself looks great and you did a great job keeping both the project folder and the code very neat, organized, and readable. Very good work using media queries to make sure the site stays looking good no matter where its being viewed as well.

There isn't too much to report as far as issues with the site - mostly everything looks great. One subtle issue I did notice is with the special characters. Make sure to use html entities to represent special characters on the page to ensure that they display correctly across all browsers. Also, be careful to make sure the page title is what it should be!

From here you are in a great place to explore what Bootstrap has to offer. Here's some more info on how to create a flashier navigation bar by including Bootstrap in your project - https://v4-alpha.getbootstrap.com/components/navbar/

Keep up the good work!

**Comment by mohilles** [comment]
Thank you 
i will work with my issues
